
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.6 EDK_P.68d
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_TEST_PINS_DEVICE_ID,
		XPAR_TEST_PINS_BASEADDR,
		XPAR_TEST_PINS_INTERRUPT_PRESENT,
		XPAR_TEST_PINS_IS_DUAL
	}
};


