
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = standalone
 PARAMETER OS_VER = 3.11.a
 PARAMETER PROC_INSTANCE = microblaze_0
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu
 PARAMETER DRIVER_VER = 1.15.a
 PARAMETER HW_INSTANCE = microblaze_0
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.03.a
 PARAMETER HW_INSTANCE = dlmb_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 3.03.a
 PARAMETER HW_INSTANCE = ilmb_cntlr
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipsdksebesegespozicio_plbw
 PARAMETER DRIVER_VER = 37.00.a
 PARAMETER HW_INSTANCE = ipsdksebesegespozicio_plbw_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipsdksebesegespozicio_plbw
 PARAMETER DRIVER_VER = 37.00.a
 PARAMETER HW_INSTANCE = ipsdksebesegespozicio_plbw_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipsdksebesegespozicio_plbw
 PARAMETER DRIVER_VER = 37.00.a
 PARAMETER HW_INSTANCE = ipsdksebesegespozicio_plbw_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = ipsdksebesegespozicio_plbw
 PARAMETER DRIVER_VER = 37.00.a
 PARAMETER HW_INSTANCE = ipsdksebesegespozicio_plbw_3
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = gpio
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = led4gpio
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 3.06.a
 PARAMETER HW_INSTANCE = spizybo
END


