
function top_level_config(this_block)

  % Revision History:
  %
  %   11-Apr-2015  (17:01 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\IncSensor.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('top_level');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('QuadA');
  this_block.addSimulinkInport('QuadB');

  this_block.addSimulinkOutport('DIR');
  this_block.addSimulinkOutport('IMP');

  DIR_port = this_block.port('DIR');
  DIR_port.setType('UFix_1_0');
  DIR_port.useHDLVector(false);
  IMP_port = this_block.port('IMP');
  IMP_port.setType('UFix_1_0');
  IMP_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('QuadA').width ~= 1);
      this_block.setError('Input data type for port "QuadA" must have width=1.');
    end

    this_block.port('QuadA').useHDLVector(false);

    if (this_block.port('QuadB').width ~= 1);
      this_block.setError('Input data type for port "QuadB" must have width=1.');
    end

    this_block.port('QuadB').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % System Generator found no apparent clock signals in the HDL, assuming combinational logic.
  % -----------------------------
   if (this_block.inputRatesKnown)
     inputRates = this_block.inputRates; 
     uniqueInputRates = unique(inputRates); 
     outputRate = uniqueInputRates(1);
     for i = 2:length(uniqueInputRates)
       if (uniqueInputRates(i) ~= Inf)
         outputRate = gcd(outputRate,uniqueInputRates(i));
       end
     end  % for(i)
     for i = 1:this_block.numSimulinkOutports 
       this_block.outport(i).setRate(outputRate); 
     end  % for(i)
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('IncSensor.vhd');

return;


