%%uiopen('C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\PIMPID.slx',1)
%%uiopen('C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\PositionControlerSimulation.slx',1)
%%uiopen('C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\InkrementalisSimulation.slx',1)
%%uiopen('C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\SpeedSimulation',1)
%%uiopen('C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\PWMSimulation',1)
uiopen('C:\Diak\gl\SPARTAN3E500K_slave\SystemGenrator\SebessegEsPozicio\TSgenerator',1)
set(0,'ShowHiddenHandles','on');
set(gcf,'menubar','figure');
set(0,'ShowHiddenHandles','on');
set(gcf,'menubar','figure');