

# Global period constraint
create_clock -name clk -period 20.0 [get_ports clk]
# LOC constraints
set_property LOC Fixed [get_ports clk]
set_property LOC P9 [get_ports {pmod1[7]}]
set_property LOC P12 [get_ports {pmod1[6]}]
set_property LOC P13 [get_ports {pmod1[5]}]
set_property LOC P19 [get_ports {pmod1[4]}]
set_property LOC P31 [get_ports {pmod1[3]}]
set_property LOC P29 [get_ports {pmod1[2]}]
set_property LOC P25 [get_ports {pmod1[1]}]
set_property LOC P23 [get_ports {pmod1[0]}]
set_property LOC P8 [get_ports {pmod2[7]}]
set_property LOC P11 [get_ports {pmod2[6]}]
set_property LOC P15 [get_ports {pmod2[5]}]
set_property LOC P18 [get_ports {pmod2[4]}]
set_property LOC P30 [get_ports {pmod2[3]}]
set_property LOC P28 [get_ports {pmod2[2]}]
set_property LOC P24 [get_ports {pmod2[1]}]
set_property LOC P22 [get_ports {pmod2[0]}]
set_property LOC P34 [get_ports {pmod3[7]}]
set_property LOC P36 [get_ports {pmod3[6]}]
set_property LOC P40 [get_ports {pmod3[5]}]
set_property LOC P42 [get_ports {pmod3[4]}]
set_property LOC P61 [get_ports {pmod3[3]}]
set_property LOC P55 [get_ports {pmod3[2]}]
set_property LOC P49 [get_ports {pmod3[1]}]
set_property LOC P47 [get_ports {pmod3[0]}]
