

# Global period constraint
create_clock -name clk -period 20.0 [get_ports clk]
# LOC constraints
set_property LOC Fixed [get_ports clk]
set_property LOC M16 [get_ports {ja1[7]}]
set_property LOC M14 [get_ports {ja1[6]}]
set_property LOC L16 [get_ports {ja1[5]}]
set_property LOC K13 [get_ports {ja1[4]}]
set_property LOC M15 [get_ports {ja1[3]}]
set_property LOC L17 [get_ports {ja1[2]}]
set_property LOC K12 [get_ports {ja1[1]}]
set_property LOC L15 [get_ports {ja1[0]}]
set_property LOC U18 [get_ports {jb1[7]}]
set_property LOC T18 [get_ports {jb1[6]}]
set_property LOC R16 [get_ports {jb1[5]}]
set_property LOC P17 [get_ports {jb1[4]}]
set_property LOC T17 [get_ports {jb1[3]}]
set_property LOC R15 [get_ports {jb1[2]}]
set_property LOC R18 [get_ports {jb1[1]}]
set_property LOC M13 [get_ports {jb1[0]}]
set_property LOC J12 [get_ports {jc1[7]}]
set_property LOC G16 [get_ports {jc1[6]}]
set_property LOC F14 [get_ports {jc1[5]}]
set_property LOC H15 [get_ports {jc1[4]}]
set_property LOC H16 [get_ports {jc1[3]}]
set_property LOC G13 [get_ports {jc1[2]}]
set_property LOC J16 [get_ports {jc1[1]}]
set_property LOC G15 [get_ports {jc1[0]}]
